---
default:
  image: python:3.11
  tags:
    - k8s-agent-runner

before_script:
  - pip install --no-cache-dir -r requirements.txt

stages:
  # Unit tests
  - test_pytest
  # Install Module
  - setup_install

test_pytest:
  stage: test_pytest
  script: pytest

setup_install:
  stage: setup_install
  script: python setup.py install
