# Author: Fábio Madeira <fmadeira@ebi.ac.uk>, 2020
# test/run locally with
# gitlab-runner exec docker test_pytest

image: python:3.7-alpine

before_script:
  - pip install -r requirements.txt

stages:
  # Unit tests
  - test_pytest

test_pytest:
  stage: test_pytest
  script: pytest
