# Author: Fábio Madeira <fmadeira@ebi.ac.uk>, 2020
# test/run locally with
# gitlab-runner exec docker test_pytest

image: python:3.9

before_script:
  - pip install --no-cache-dir -r requirements.txt

stages:
  # Unit tests
  - test_pytest
  # Install Module
  - setup_install

test_pytest:
  stage: test_pytest
  script: pytest

setup_install:
  stage: setup_install
  script: python setup.py install
